name: Daily Weather Sync

on:
  schedule:
    - cron: '20 6 * * *'  # Runs at 6:20 AM UTC
  workflow_dispatch:      # Allows you to run it manually with a button click

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests pandas pyarrow

      - name: Run Weather Script
        env:
          API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        run: python weather_extractor.py

      - name: Commit and Push Parquet File
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/*.parquet
          git commit -m "Auto-update weather data" || exit 0
          git push